# Default values for ves-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onap/org.onap.integration.nfsimulator.vesclient
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ves-client"
config:
  mongoDbServer: nf-simulator-mongodb
  useCertForAuth: true
  containerPort: 5000

storeMap:
  directory: "/app/store"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mongo-express:
  fullnameOverride: "nf-simulator-mongo-express"
  mongodbServer: nf-simulator-mongodb
  nameOverride: mongo-express
  mongodbAdminPassword: zXcVbN123!

mongodb:
  fullnameOverride: "nf-simulator-mongodb"
  persistence:
    enabled: false
  auth:
    rootPassword: zXcVbN123!
    database: pnf_simulator
    username: root
