apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
binaryData:
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "resources/" $key }}
  {{ $key | trimPrefix "resources/" }}: {{ $files.Get $key | b64enc | quote }} 
  {{- end }}
  {{- end }}
